spring:
  datasource:
    name: db-dev
    url: jdbc:postgres://ogqzcqwhasycpy:e1d9ccd43d3341bf835ae689f8d551a09bc14921a48edd637df436a8d60b3396@ec2-174-129-226-234.compute-1.amazonaws.com:5432/de4j5a0pfid8p5
    username: ogqzcqwhasycpy
    password: e1d9ccd43d3341bf835ae689f8d551a09bc14921a48edd637df436a8d60b3396
    driver-class-name: org.postgresql.Driver
    platform: 
    hikari:
        connection-timeout: 20000
        maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: true
        ddl-auto: update 
        temp.use_jdbc_metadata_defaults: false
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: true